### PR TITLE
Fix for working against an Aqua on-prem version

### PR DESCRIPTION
**Pull request by Ukhanskyi**
[Issue](https://github.com/KennaSecurity/toolkit/issues/550)

Fix for working against an Aqua on-prem version

1 variant aqua:
image

2 variant aqua (cloud):
image

### CODE REVIEW

**Comment by Ukhanskyi** [comment]
@jgarber-cisco, could I ask you review this little changes for aqua?

**Comment by Ukhanskyi** [comment]
@dianaroz, I've noticed that you were a reviewer for few previous PR's. Could I ask you to review this little change for aqua connector? Please

**Comment by Ukhanskyi** [comment]
@jgarber-cisco, @jgarber, @ababhis2, @dianaroz I've noticed that you were a reviewer for few previous PR's. Could I ask someone to review this little change for aqua connector? Please 🙏🏼

**Review by jgarber-cisco — APPROVED** [review]
So it sounds like there was a regression with on-prem Aqua when the cloud functionality was added? Thanks for fixing it!

**Comment by Ukhanskyi** [comment]
> So it sounds like there was a regression with on-prem Aqua when the cloud functionality was added? Thanks for fixing it!

Yeah that is correct, thank you for your review 🙇‍♂️

**Pull request merged**
