### PR TITLE
Armis Connector Task

### PR DESCRIPTION
**Pull request by parthmodi2-crest**

### CODE REVIEW

**Review by annapoltieva — APPROVED** [review]
LGTM

**Comment by parthmodi2-crest** [comment]
Updated PR with following changes

- Merged Main Branch (Ruby version was upgraded from 2.6 to 3.1) [1709a88](https://github.com/KennaSecurity/toolkit/pull/400/commits/1709a886c39c44983709b6dfe1fd90fd9d8b369c)
- Fixed lint errors [d7b2ab8](https://github.com/KennaSecurity/toolkit/pull/400/commits/d7b2ab81682537b48d18b4dca1ace502bebe8444)

**Comment by parthmodi2-crest** [comment]
@annapoltieva Let me know if you have any feedback!

**Review by annapoltieva — APPROVED** [review]
Looks good

**Comment by parthmodi2-crest** [comment]
No changes are remaining from my end, you can merge!

**Pull request merged**
