### PR TITLE
edgescan connector update

### PR DESCRIPTION
**Pull request by ShayVD**
# Context

Rather than mapping edgescan assets/location specifiers to Kenna assets, clients want the ability to map edgescan hosts to Kenna assets.

# Changes

Add a toggle to the edgescan connector that adds edgescan hosts (and their corresponding vulnerabilities and definitions) as Kenna assets.

### CODE REVIEW

**Comment by ShayVD** [comment]
Hey @mukhansk, could we get another review here please, thank you.

**Comment by mukhansk** [comment]
> Hey @mukhansk, could we get another review here please, thank you.

Of course, give me a little time 😉

**Comment by mukhansk** [comment]
I have no comments on your code. Everything seems well done. I would like to see how the displayed data has changed. Could you upload the screenshots?

**Comment by ShayVD** [comment]
Nothing really changes with regards to how the data is displayed, just how we pull the data from edgescan.

Example:
image

**Review by mukhansk — APPROVED** [review]
LGTM

**Pull request merged**
